### PR TITLE
fix: menu button and theme button in date input  isnt need to rewrite

### LINKED ISSUE #347: Date input menu button is defined in +layout.svelte
The `.menu-button-container` and `.dark-mode-button-container` CSS and HTML that is a dependency of the `DateInput` component is defined in the `+layout.svelte` file. This makes it difficult to use in other projects.

If I understand correctly this is is done this way so that opening a date input popup automatically closes the theme color picker.  It would be better if this were done at a different level (e.g. in a store or in the layout) and not in the `DateInput` component.

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #347

### CODE REVIEW

File: src/lib/components/ui/input/date-input.svelte [hunk 1]
```diff
@@ -332,7 +326,7 @@
 		position: fixed;
 		top: 0;
 		left: 0;
-		z-index: 1;
+		z-index: 101;
```
Comment (vojtechsimetka) [inline src/lib/components/ui/input/date-input.svelte:329]: Do we even need this? Isn't 1 good enough and if not then some lower number than 100? :)

**Review by vojtechsimetka — APPROVED** [review]

File: src/lib/components/ui/input/date-input.svelte (hunk 1 above)
Comment (hlavkat) [reply src/lib/components/ui/input/date-input.svelte:329]: no, because mode-button-container and menu-button-container in layout have z-index 100

**Review by agazso — APPROVED** [review]
