### PR TITLE
fix: date input return type Date instead of string

### LINKED ISSUE #348: Date input returns string instead of `Date`
The bindable `value` property of the `DateInput` returns a `string` instead of a `Date`. This means you lose the timezone information and forces a formatting which ignores your locale. It would be better if the returned object were a `Date` and then let the user convert to whatever they want.

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #348

### CODE REVIEW

File: src/lib/components/ui/input/date-input.svelte [hunk 1]
```diff
@@ -126,12 +129,23 @@
...
+		const day = String(date.getDate()).padStart(2, '0')
+		return `${year}-${month}-${day}`
+	}
+
 	function inputChange(event: Event) {
 		const input = event.target as HTMLInputElement
 		const newDate = parseDate(input.value)
 		selectedDate = newDate
 		selectedMonth = newDate.getMonth()
 		selectedYear = newDate.getFullYear()
```
Comment (vojtechsimetka) [inline src/lib/components/ui/input/date-input.svelte:147]: BTW I think we can simplify here. These values could be `$derived` from `value` instead of using `$state`. Also the `currentDate` is unnecessary and we can use `value` directly.

**Review by vojtechsimetka — COMMENTED** [review]
Please try and reduce the amount of state variables as suggested. Otherwise this is good.

**Review by agazso — APPROVED** [review]
