### PR TITLE
fix: checkbox visual bug on iOS

### LINKED ISSUE #46: Checkbox visual bug on iOS
IMG_4EFAAA83CDF0-1

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #46

### CODE REVIEW

File: src/lib/components/ui/checkbox.svelte [hunk 1]
```diff
@@ -84,10 +84,11 @@
 			}
 		}
 	}
+
 	input[type='checkbox'] {
 		position: relative;
 		appearance: none;
-		z-index: 0;
+		z-index: auto;
```
Comment (vojtechsimetka) [inline src/lib/components/ui/checkbox.svelte:91]: I think this is default, right? So we can just remove the `z-index`

**Review by vojtechsimetka — APPROVED** [review]
